[workspace]
resolver = "2"

members = [
    "demes", "demes-ffi",
    "demes-forward",
    "demes-forward-capi"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
lto = "fat"
codegen-units = 1
